Web Project/WebProject/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace WebProject.Controllers
{
    public class LanguageController : Controller
    {
        // GET: Language
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Change(string langAbbr)
        {
            if (langAbbr != null)
            {
                Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(langAbbr);
                Thread.CurrentThread.CurrentUICulture = new CultureInfo(langAbbr);
            }

            HttpCookie cooki = new HttpCookie("language");
            cooki.Value = langAbbr;
            Response.Cookies.Add(cooki);

            return Redirect(Request.UrlReferrer.PathAndQuery);
        }
    }
}

Web Project/WebProject/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebProject.Controllers
{
    public class SharedController : Controller
    {
		// GET: Shared
		public ActionResult Search(string arama)
		{ 
			Models.Arama ara = new Models.Arama();
			ara.aranilan = arama;
			return View(ara);
		}
    }
}

Web Project/WebProject/Controllers/VideosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebProject.Controllers;
using System.IO;
using System.Drawing;
using NReco.VideoInfo;
using NReco.VideoConverter;
//using Accord.Video.FFMPEG;

namespace WebProject.Controllers
{
    public class VideosController : Controller
    {
        dbModel db = new dbModel();


        // GET: Videos

        public ActionResult Sil(int videoId)
        {
            var videos = new List<Videolar>();
            videos = db.Videolar.ToList();

            var comms = new List<Yorumlar>();
            comms = db.Yorumlar.ToList();

            foreach (Videolar item in videos)
            {
                if (videoId == item.ID)
                {
                    foreach (Yorumlar com in comms)
                    {
                        if (com.VideoID == item.ID)
                        {
                            db.Yorumlar.Remove(db.Yorumlar.Find(com.ID));
                        }
                    }
                    FileInfo myfile = new FileInfo(Path.Combine(Server.MapPath("~/requiredFiles/videos/"), item.VideoYolu.Replace("/requiredFiles/videos/", string.Empty)));
                    db.Videolar.Remove(db.Videolar.Find(item.ID));
                    myfile.Delete();
                }
            }
            db.SaveChanges();
            return Redirect("/Account/UserPage");
        }

        public ActionResult Playing(int videoId)
        {
            Videolar video = new Videolar();
            video.ID = videoId;
            db.Videolar.Find(videoId).IzlenmeSayisi++;
            db.SaveChanges();
            return View(video);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Playing(FormCollection form, int videoId)
        {
            var vList = new List<Videolar>();
            var yList = new List<Yorumlar>();
            var yor = new Yorumlar();
            vList = db.Videolar.ToList();
            yList = db.Yorumlar.ToList();

            var users = new List<Kullanicilar>();
            users = db.Kullanicilar.ToList();
            int id = -1;
            foreach (Kullanicilar item in users)
            {
                if (Session["Giris"].ToString() == item.KullaniciAdi)
                {
                    id = item.ID;
                    break;
                }
            }

            yor.ID = db.Yorumlar.Max(x => x.ID) + 1;
            yor.YazarID = id;
            yor.VideoID = videoId;
            yor.YorumTarihi = DateTime.Now;
            yor.Yorum = form.Get("yorum");

            if (ModelState.IsValid)
            {
                db.Yorumlar.Add(yor);
                db.SaveChanges();
                return RedirectToAction("Playing", new { videoId = videoId });
            }

            return RedirectToAction("Playing", new { videoId = videoId });
        }

        [HttpGet]
        public ActionResult UploadPage()
        {
            return View();
        }



        [HttpPost]
        public ActionResult UploadPage(FormCollection form, HttpPostedFileBase dosya, HttpPostedFileBase resim)
        {
            Videolar videoss = new Videolar();
            //VideoFileReader reader = new VideoFileReader();


            var users = new List<Kullanicilar>();
            users = db.Kullanicilar.ToList();
            int id = -1;
            foreach (Kullanicilar item in users)
            {
                if (item.KullaniciAdi == Session["Giris"].ToString())
                {
                    id = item.ID;
                }
            }
            if (ModelState.IsValid)
            {
                videoss.ID = db.Videolar.Max(x => x.ID) + 1;
                videoss.VideoTarihi = DateTime.Now;
                videoss.IzlenmeSayisi = 0;
                videoss.VideoYukleyen = id;
                videoss.Baslik = form.Get("baslik");
                //Path.Combine(Server.MapPath("~\requiredFiles\videos"), fileName);
                var fileName = "";
                if (dosya != null)
                {
                    fileName = dosya.FileName;
                    var path = "/requiredFiles/videos/" + fileName;
                    videoss.VideoYolu = path;

                    dosya.SaveAs(Path.Combine(Server.MapPath("~/requiredFiles/videos/"), fileName));

                    var ffProbe = new FFProbe();
                    var videoInfo = ffProbe.GetMediaInfo(Path.Combine(Server.MapPath("~/requiredFiles/videos/"), fileName));

                    videoss.VideoSuresi = videoInfo.Duration;
                    db.Videolar.Add(videoss);
                    db.SaveChanges();
                    if (resim != null)
                    {
                        var resimname = resim.FileName;
                        resim.SaveAs(Path.Combine(Server.MapPath("~/requiredFiles/capturedFrames/"), resimname));
                        var pathr = "/requiredFiles/capturedFrames/" + resimname;
                        videoss.VideoThumbnail = pathr;
                    }
                    else
                    {
                        var pathResim = "~/requiredFiles/capturedFrames/";
                        //string filename = Path.GetFileName(path);
                        //double Framerate = reader.FrameRate.Value;
                        //int intFrameRate = Convert.ToInt32(Framerate);

                        //for (int i = 0; i <= intFrameRate * 12 /*frameSecondHalf*/; i++)
                        //{
                        //    Bitmap videoFrame = reader.ReadVideoFrame();
                        //    //if (i == (intFrameRate * frameSecondHalf))
                        //    if (i == (intFrameRate * 10))
                        //    {


                        //        videoFrame.Save(i + ".png");

                        //        string capturedframeName = i.ToString() + ".png";
                        //        if (!System.IO.File.Exists(@"~/requiredFiles/capturedFrames/" + filename + "_" + capturedframeName))
                        //        {

                        //            System.IO.File.Move(@"C:\Users\EnýY\source\repos\getFrame01\getFrame01\bin\Debug\" + capturedframeName, @"~/requiredFiles/capturedFrames/" + filename + "_" + capturedframeName);
                        //            videoss.VideoThumbnail = "~/requiredFiles/capturedFrames/" + filename + "_" + capturedframeName;
                        //        }
                        //    }
                        //}
                        var ffmpeg = new FFMpegConverter();
                        ffmpeg.GetVideoThumbnail(path, pathResim, 30);
                    }


                    db.Videolar.Add(videoss);
                    db.SaveChanges();
                    return Redirect("/Home/Index");
                }
                else
                {

                }
            }

            return RedirectToAction("UploadPage");
        }
    }
}

Web Project/WebProject/Views/Shared/_Layout.cshtml
@using WebProject.Resources;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - VideoVision</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @functions{
        bool tekmi(int sayi)
        {
            double x = Convert.ToDouble(sayi);
            if (x / 2 == sayi / 2) return false;
            return true;
        }

    }
    @if (Request.Cookies["remember"] != null)
    {
        var usr = Request.Cookies["remember"].Value;
        //usr = usr.Replace("?EufeqwDQx", string.Empty);
        byte[] deger = System.Text.UnicodeEncoding.BigEndianUnicode.GetBytes(usr);
        for (int i = 0; i < deger.Length; i++)
        {
            if (tekmi(i))
            {
                deger[i] -= 13;
            }
        }
        string cozulen = System.Text.UnicodeEncoding.BigEndianUnicode.GetString(deger);

        dbModel db = new dbModel();

        var users = new List<Kullanicilar>();
        users = db.Kullanicilar.ToList();
        bool gec = false;
        foreach (Kullanicilar item in users)
        {
            if (item.KullaniciAdi == cozulen)
            {
                Session["Giris"] = cozulen;
                gec = true; break;
            }
        }
        if (!gec)
        {
            Session.Remove("Giris");
            Response.Cookies["remember"].Expires = DateTime.Now.AddDays(-1);
        }
    }


</head>
<body style="background-color:transparent;">


    
    <nav class="navbar navbar-fixed-top" style="background-color:white;border-bottom:solid 0.5px;border-bottom-color:lightgray;padding-bottom:10px;display:block">
        <div class="row">
            <div class="col-lg-2">
                <a href='@Url.Action("Index", "Home")' title="VideoVision"><img src="~/Documents/sitelogo.png" width="125px" style="margin-left:42%;" /></a>
            </div>
           
            <div class="col-lg-7" style="margin:auto">
                <form class="search">
                    <input class="searchTerm" placeholder="@Lang.SearchText" required /><input class="searchButton" type="submit" />
                </form>
            </div>
            <div class="col-lg-1 " style="margin-top:15px;margin-left:5%;position:relative;max-width:90px ">
                
                    <div class="dropdown">
                        <button class="btn btn-default btn-city dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            <img src="~/requiredFiles/turkce-inglizce.png" width="25px" height="auto" />
                             @Lang.SelectLanguage
                            <span class="caret caret-search"></span>
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <li><a href="@Url.Action("Change", "Language", new { langAbbr = "tr" }, null)"><img src="~/requiredFiles/Custom-Icon-Design-Flag-3-Turkey-Flag.ico" width="25px" height="auto" /> TR </a></li>
                            @*@Url.Action(ViewContext.RouteData.Values["action"].ToString(), ViewContext.RouteData.Values["controller"].ToString(), new { language = "TR" }, null)*@
                            <li role="separator" class="divider">
                            </li>
                            <li><a href="@Url.Action("Change", "Language", new { langAbbr = "" }, null)"><img src="~/requiredFiles/Custom-Icon-Design-All-Country-Flag-United-Kingdom-flag.ico" width="25px" height="auto" /> EN</a></li>
                        </ul>
                    
                </div>
            </div>
            


        
            <div class="col-lg-1" style="margin-left:10px;" >
                @if (Session["Giris"] == null)
        {
            <button style="margin-left:50%;margin-top:17px;text-align: center" onclick="location.href='@Url.Action("Login","Account")';return false;" class="btn btn-primary btn-default"><span class="fa fa-sign-in"></span> @Lang.SignIn</button>
}
else
{
        <style>
            .nav {
                left: 50%;
                margin-left: -50px;
                top: 0px;
                position: inherit;
            }

                .nav > li > a:hover, .nav > li > a:focus, .nav .open > a, .nav .open > a:hover, .nav .open > a:focus {
                    background: #fff;
                }

            .dropdown {
                background: #fff;
                border: 1px solid #ccc;
                border-radius: 4px;
                width: 100px;
            }

            .dropdown-menu > li > a {
                color: #428bca;
            }

            .dropdown ul.dropdown-menu {
                border-radius: 4px;
                box-shadow:2px;
                margin-top: 20px;
                width: 200px;
            }

                .dropdown ul.dropdown-menu:before {
                    content: "";
                    border-bottom: 10px solid #fff;
                    border-right: 10px solid transparent;
                    border-left: 10px solid transparent;
                    position: absolute;
                    top: -10px;
                    right: 16px;
                    z-index: 10;
                }

                .dropdown ul.dropdown-menu:after {
                    content: "";
                    border-bottom: 12px solid #ccc;
                    border-right: 12px solid transparent;
                    border-left: 12px solid transparent;
                    position: absolute;
                    top: -12px;
                    right: 14px;
                    z-index: 9;
                }
            
        </style>
var user = Session["Giris"];

string ilk = ""; string son = "";
if (user.ToString().Length > 15)
{
    for (int i = 0; i < user.ToString().Length + 1; i++)
    {
        if (i <= 15) { ilk += user.ToString()[i]; }
        else if (i == 16) { son += '\n'; }
        else { son += user.ToString()[i - 1]; }
    }
    user = ilk + son;
}
else
{
    ilk = user.ToString();
}
        <ul class="nav navbar-nav" style="margin-top:10px;margin-bottom:10px">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">@ilk<span class="glyphicon glyphicon-user pull-right"></span>@son</a>
                <ul class="dropdown-menu">
                    <li><a href="@Url.Action("UploadPage","Videos")">@Lang.Upload <span class="fa fa-upload pull-right"></span></a></li>
                    <li class="divider"></li>
                    <li><a href="@Url.Action("UserPage","Account")">@Lang.AccountSetting <span class="glyphicon glyphicon-cog pull-right"></span></a></li>
                    <li class="divider"></li>
                    <li><a href="@Url.Action("SignOut","Account")">@Lang.SignOut <span class="glyphicon glyphicon-log-out pull-right"></span></a></li>
                </ul>
            </li>
        </ul>
}
            </div>
        </div>
    </nav>
    <div class="container body-content" style="margin-top:5%;">
        @RenderBody()
        <footer class="navbar-static-bottom">
            <hr />
            <p style="text-align:center">&copy; @DateTime.Now.Year - VideoVision ® @Lang.AllRightsReserved.</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)
</body>
</html>