Web Project/WebProject/Controllers/VideosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebProject.Controllers;
using System.IO;
using System.Drawing;
using NReco.VideoInfo;
using NReco.VideoConverter;
//using Accord.Video.FFMPEG;

namespace WebProject.Controllers
{
    public class VideosController : Controller
    {
        dbModel db = new dbModel();


        // GET: Videos

        public ActionResult Sil(int videoId)
        {
            var videos = new List<Videolar>();
            videos = db.Videolar.ToList();

            var comms = new List<Yorumlar>();
            comms = db.Yorumlar.ToList();

            foreach (Videolar item in videos)
            {
                if (videoId == item.ID)
                {
                    foreach (Yorumlar com in comms)
                    {
                        if (com.VideoID == item.ID)
                        {
                            db.Yorumlar.Remove(db.Yorumlar.Find(com.ID));
                        }
                    }
                    FileInfo myfile = new FileInfo(Path.Combine(Server.MapPath("~/requiredFiles/videos/"), item.VideoYolu.Replace("/requiredFiles/videos/", string.Empty)));
                    db.Videolar.Remove(db.Videolar.Find(item.ID));
                    myfile.Delete();
                }
            }
            db.SaveChanges();
            return Redirect("/Account/UserPage");
        }

        public ActionResult Playing(int videoId)
        {
            Videolar video = new Videolar();
            video.ID = videoId;
            db.Videolar.Find(videoId).IzlenmeSayisi++;
            db.SaveChanges();
            return View(video);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Playing(FormCollection form, int videoId)
        {
            var vList = new List<Videolar>();
            var yList = new List<Yorumlar>();
            var yor = new Yorumlar();
            vList = db.Videolar.ToList();
            yList = db.Yorumlar.ToList();

            var users = new List<Kullanicilar>();
            users = db.Kullanicilar.ToList();
            int id = -1;
            foreach (Kullanicilar item in users)
            {
                if (Session["Giris"].ToString() == item.KullaniciAdi)
                {
                    id = item.ID;
                    break;
                }
            }

            yor.ID = db.Yorumlar.Max(x => x.ID) + 1;
            yor.YazarID = id;
            yor.VideoID = videoId;
            yor.YorumTarihi = DateTime.Now;
            yor.Yorum = form.Get("yorum");

            if (ModelState.IsValid)
            {
                db.Yorumlar.Add(yor);
                db.SaveChanges();
                return RedirectToAction("Playing", new { videoId = videoId });
            }

            return RedirectToAction("Playing", new { videoId = videoId });
        }

        [HttpGet]
        public ActionResult UploadPage()
        {
            return View();
        }



        [HttpPost]
        public ActionResult UploadPage(FormCollection form, HttpPostedFileBase dosya, HttpPostedFileBase resim)
        {
            Videolar videoss = new Videolar();
            //VideoFileReader reader = new VideoFileReader();


            var users = new List<Kullanicilar>();
            users = db.Kullanicilar.ToList();
            int id = -1;
            foreach (Kullanicilar item in users)
            {
                if (item.KullaniciAdi == Session["Giris"].ToString())
                {
                    id = item.ID;
                }
            }
            if (ModelState.IsValid)
            {
                videoss.ID = db.Videolar.Max(x => x.ID) + 1;
                videoss.VideoTarihi = DateTime.Now;
                videoss.IzlenmeSayisi = 0;
                videoss.VideoYukleyen = id;
                videoss.Baslik = form.Get("baslik");
                //Path.Combine(Server.MapPath("~\requiredFiles\videos"), fileName);
                var fileName = "";
                if (dosya != null)
                {
                    fileName = dosya.FileName;
                    var path = "/requiredFiles/videos/" + fileName;
                    videoss.VideoYolu = path;

                    dosya.SaveAs(Path.Combine(Server.MapPath("~/requiredFiles/videos/"), fileName));

                    var ffProbe = new FFProbe();
                    var videoInfo = ffProbe.GetMediaInfo(Path.Combine(Server.MapPath("~/requiredFiles/videos/"), fileName));

                    videoss.VideoSuresi = videoInfo.Duration;
                    db.Videolar.Add(videoss);
                    db.SaveChanges();
                    if (resim != null)
                    {
                        var resimname = resim.FileName;
                        resim.SaveAs(Path.Combine(Server.MapPath("~/requiredFiles/capturedFrames/"), resimname));
                        var pathr = "/requiredFiles/capturedFrames/" + resimname;
                        videoss.VideoThumbnail = pathr;
                    }
                    else
                    {
                        var pathResim = "~/requiredFiles/capturedFrames/";
                        //string filename = Path.GetFileName(path);
                        //double Framerate = reader.FrameRate.Value;
                        //int intFrameRate = Convert.ToInt32(Framerate);

                        //for (int i = 0; i <= intFrameRate * 12 /*frameSecondHalf*/; i++)
                        //{
                        //    Bitmap videoFrame = reader.ReadVideoFrame();
                        //    //if (i == (intFrameRate * frameSecondHalf))
                        //    if (i == (intFrameRate * 10))
                        //    {


                        //        videoFrame.Save(i + ".png");

                        //        string capturedframeName = i.ToString() + ".png";
                        //        if (!System.IO.File.Exists(@"~/requiredFiles/capturedFrames/" + filename + "_" + capturedframeName))
                        //        {

                        //            System.IO.File.Move(@"C:\Users\EnýY\source\repos\getFrame01\getFrame01\bin\Debug\" + capturedframeName, @"~/requiredFiles/capturedFrames/" + filename + "_" + capturedframeName);
                        //            videoss.VideoThumbnail = "~/requiredFiles/capturedFrames/" + filename + "_" + capturedframeName;
                        //        }
                        //    }
                        //}
                        var ffmpeg = new FFMpegConverter();
                        ffmpeg.GetVideoThumbnail(path, pathResim, 30);
                    }


                    db.Videolar.Add(videoss);
                    db.SaveChanges();
                    return Redirect("/Home/Index");
                }
                else
                {

                }
            }

            return RedirectToAction("UploadPage");
        }
    }
}

Web Project/WebProject/Controllers/YorumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebProject.Controllers
{
    public class YorumController : Controller
    {
		dbModel db = new dbModel();
        // GET: Yorum
        public ActionResult Index()
        {
            return View();
        }
		public ActionResult Sil(int yorumId)
		{
			var comms = new List<Yorumlar>();
			comms = db.Yorumlar.ToList();

			foreach (Yorumlar item in comms)
			{
				if (yorumId == item.ID) 
				{
					db.Yorumlar.Remove(item);
				}
			}
			db.SaveChanges();
			return Redirect("/Account/UserPage");
		}
		public ActionResult NormalSil(int yorumId,int videoId)
		{
			var comms = new List<Yorumlar>();
			comms = db.Yorumlar.ToList();

			foreach (Yorumlar item in comms)
			{
				if (yorumId == item.ID)
				{
					db.Yorumlar.Remove(item);
				}
			}
			db.SaveChanges();
			return RedirectToAction("Playing","Videos",new { videoId = videoId });
		}
	}
}

Web Project/WebProject/Views/Videos/Playing.cshtml
@using WebProject.Resources;
@model WebProject.Videolar
@{
		ViewBag.Title = "Playing";
		Layout = "~/Views/Shared/_Layout.cshtml";

		dbModel db = new dbModel();
		var users = new List<Kullanicilar>();
		users = db.Kullanicilar.ToList();

		var videos = new List<Videolar>();
		videos = db.Videolar.ToList();

		var comments = new List<Yorumlar>();
		comments = db.Yorumlar.ToList();
		var yorums = new Yorumlar();








	}



@functions{

			string fark(DateTime date)
			{ 
			DateTime now = DateTime.Now;
			TimeSpan diff = now - date;
			int days = diff.Days;
			int hours = diff.Hours;
			int minutes = diff.Minutes;
		if (days >= 7)
		{

			if (days >= 30)
			{
				if (days >= 365)
				{
					return ((int)(days / 365)).ToString() + " "+Lang.YearsAgo;
				}
				return ((int)(days / 30)).ToString() +" "+ Lang.MonthsAgo;
			}
			return ((int)(days / 7)).ToString() +" "+ Lang.Weekago;
		}
		else if (days <= 0)
		{
			if (hours >= 1) return hours.ToString() +" "+ Lang.HoursAgo;
			else return minutes.ToString() + " "+ Lang.MinutesAgo;
		}
		return days.ToString() +" "+ Lang.DaysAgo;
	}

	int counter = 0;
	Random rnd = new Random();

	int generateNum(int sinir)
	{
		int rndSayi = rnd.Next(1, sinir);
		return rndSayi;
	}
}

<head>
    <link href="~/Content/playerStyle.css" rel="stylesheet" />
    <link href="~/Content/commentStyle.css" rel="stylesheet" />

    <link href="~/Content/commentWrite.css" rel="stylesheet" />



</head>

<h2>Playing</h2>

<div class="container-fluid">

    <div class="col-lg-9">
        @foreach (var item in videos)
            {
                if (item.ID == Model.ID)
                {
                <video poster="@item.VideoThumbnail" controls>
                    <!-- Video files -->
                    <source src="@item.VideoYolu">




                </video>
                foreach (var ss in users)
                {
                    if (ss.ID == item.VideoYukleyen)
                    {
                        <h1>@item.Baslik</h1><br /><span style="color:dodgerblue;font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;font-size:large">@ss.KullaniciAdi </span><span style="float:right;font-size:medium;"><strong style="color:crimson"> @item.IzlenmeSayisi.ToString("N").Replace(".00",string.Empty).Replace(",",".")</strong> @Lang.Views </span>
                        <br /><span style="float:right;font-size:medium;"><strong style="background-color:orange"> @fark(item.VideoTarihi)</strong></span>
                    }
                }

            }
            counter++;
        }

        <br /><br />

        @using (Html.BeginForm())
        {
        <div>
            @Html.AntiForgeryToken()
            <form role="form" id="form" class="contact-form"  method="get">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div>
                    <div class="form-group">
                       <input type="text" class="form-control" name="yorum" placeholder="@Lang.WriteCommnet " required/>
                    </div>
                </div>
                <div>
                    <button type="submit" class="btn main-btn pull-right">@Lang.Submit</button>
                </div>
                </form>
            </div>
        }
	    <br /><br />

        <div style="margin-top:13px">
            <section class="comments">
				@{ 
					int yorum = 0;
				}
                @foreach (var iVideo in videos)
				{
					if (iVideo.ID == Model.ID)
					{
						foreach (var item in comments)
						{
							if (item.VideoID == iVideo.ID)
							{
								<article class="comment">
									<a class="comment-img" href="#non">
										<img src="~/requiredFiles/Icons-Land-Vista-People-Person-Male-Light.ico" alt="" width="50" height="50" />
									</a>
									<div class="comment-body">
										<div class="text">
											<p>@item.Yorum
											
											</p>
											@if (Session["Giris"].ToString() == db.Kullanicilar.Find(item.YazarID).KullaniciAdi)
											{
												<button style="float:right" class="fa fa-times btn btn-sm btn-danger" title="Yorumu Sil" onclick="location.href='@Url.Action("NormalSil", "Yorum", new { yorumId = item.ID , videoId=item.VideoID })'"></button>
											}
										</div>
										<p class="attribution">
											by <span style="color:dodgerblue;" href="#non">@item.Kullanicilar.KullaniciAdi</span> @item.YorumTarihi
										</p>
									</div>
								</article>
								yorum++;
							}
						}
					}
				}
				@if (yorum == 0)
				{
					
					<span class="text-danger" style="padding-left:34%">@Lang.NoComment</span>
				}
            </section>
        </div>
        </div>
        <div class="col-lg-3">
			@{
				int sayi = 0;
				videos = db.Videolar.OrderByDescending(x => x.VideoTarihi).Take(5).ToList();
				foreach (Videolar item in videos)
				{
					if (item.ID != Model.ID && sayi < 4)
					{
						<div style="margin-bottom:10px;">
							<a href="@Url.Action("Playing","Videos",new { videoId=item.ID })">
								<img style="width: 100%;height: auto;" src="@item.VideoThumbnail" alt="@item.ID" />
							</a>
							@foreach (var ss in users)
							{
							if (ss.ID == item.VideoYukleyen)
							{
									<a title="@item.Baslik" style="color:black" href="@Url.Action("Playing","Videos",new { videoId=item.ID })">
										<strong style="font-size:medium">@item.Baslik</strong>
									</a><br />
									<span style="color:dodgerblue;font-size:medium">@ss.KullaniciAdi</span><br /><p style="float:right ;font-size:small">@item.IzlenmeSayisi @Lang.Views</p><p style="font-size:small;float:left;">@fark(item.VideoTarihi)</p>
								}
						}
						</div>
						sayi++;
					}
				}
			}
        </div>
    
</div>
<br /><br /><br /><br /><br />
























@Scripts.Render("~/bundles/videoPlayer")

<script src="~/scripts/commentsWrite.js"></script>

























































@*<head>

        <!-- Styles -->
        <link rel="stylesheet" href="https://cdn.plyr.io/2.0.18/plyr.css">




    </head>





            <section>
                <video poster="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.jpg?v1" controls >
                    <!-- Video files -->
                    <source src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.mp4" type="video/mp4">
                    <source src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.webm" type="video/webm">




                </video>


            </section>

        <!-- Plyr core script -->
        <script src="https://cdn.plyr.io/2.0.18/plyr.js"></script>

        <!-- Docs script -->
        <script src="https://cdn.plyr.io/2.0.18/demo.js"></script>

        <!-- Rangetouch to fix <input type="range"> on touch devices (see https://rangetouch.com) -->
        <script src="https://cdn.rangetouch.com/1.0.1/rangetouch.js" async></script>*@

Web Project/WebProject/Views/Videos/UploadPage.cshtml
@using WebProject.Resources;
@model WebProject.Videolar
@{
	ViewBag.Title = "UploadPage";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>

</head>

<h2>@Lang.UplaodPage</h2>

<style>

	.btn-file {
    position: relative;
    overflow: hidden;
}
.btn-file input[type=file] {
    position: absolute;
    top: 0;
    right: 0;
    min-width: 100%;
    min-height: 100%;
    font-size: 100px;
    text-align: right;
    filter: alpha(opacity=0);
    opacity: 0;
    outline: none;
    background: white;
    cursor: inherit;
    display: block;
}

#img-upload{
    width: 100%;
}
</style>


@using (Html.BeginForm("UploadPage", "Videos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	<div>
		<div class="container well">
			<div class="form-group">
				<label for="pwd">@Lang.Title</label>
				<input type="text" name="baslik" class="form-control" style="max-width:100%" />
			</div>
			<div class="form-group">
				<label for="pwd">@Lang.UploadVideo</label>
				<input type="file" name="dosya" class="form-control btn-success" style="max-width:100%" />
			</div>
			<div class="form-group">
				<label>@Lang.UplaodImage</label>
				<div class="input-group">
					<span class="input-group-btn">
						<span class="btn btn-default btn-file">
							@Lang.Browse <input type="file" name="resim" id="imgInp">
						</span>
					</span>
					<input type="text" class="form-control" readonly>
				</div>
				<img id='img-upload' />
			</div>
			<div class="pull-right">
				<button type="submit" class="btn btn-primary" data-toggle="modal" data-backdrop="static" data-keyboard="false" data-target="#myModal" onclick="startUpload()">@Lang.BeginUpload</button>
			</div>
		</div>
		<!-- Modal -->
		<div class="modal fade" id="myModal" role="dialog">
			<div class="modal-dialog">

				<!-- Modal content-->
				<div class="modal-content">
					<div class="modal-header">
						<h4 class="modal-title">@Lang.UploadInitiated</h4>
					</div>
					<div class="modal-body">
						<p>@Lang.Uploading</p>

						<div class="progress">
							<div class="progress-bar" role="progressbar" aria-valuenow="70"
								 aria-valuemin="0" aria-valuemax="100" style="width:70%">
								<span class="sr-only">70% @Lang.Completed</span>
							</div>
						</div>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-info btnprogress" onclick="clickProgress()">
							@Lang.Continue
						</button>
					</div>
				</div>

			</div>
		</div>
	</div>
}

@Scripts.Render("~/bundles/jquery")
<script src="~/scripts/resim.js"></script>
<script src="~/scripts/videoYukleme.js"></script>